// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEE.AOI.FTP.DatabaseSlim;

namespace SMEE.AOI.FTP.DatabaseSlim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240601151409_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SMEE.AOI.FTP.Data.Database.AncestorSession", b =>
                {
                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NewSessionId");

                    b.HasKey("SessionId");

                    b.ToTable("AncestorSessions");
                });

            modelBuilder.Entity("SMEE.AOI.FTP.Data.Database.SessionCommand", b =>
                {
                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AncestorSessionId");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DoneTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ErrorMsg");

                    b.Property<string>("OperParam");

                    b.Property<string>("OperType")
                        .IsRequired();

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("SessionId");

                    b.ToTable("SessionCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
